config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  mount GitWit::Engine => "/"

  resources :public_keys, except: [:edit, :update]

  scope "/projects/:project_id/repository/:repository_id" do
    resources :post_receive_hooks
  end

  scope "/repositories/:repository_id" do
    resources :post_receive_hooks, only: [] do
      put "run", on: :collection
    end
  end
end

app/models/post_receive_hook.rb
class PostReceiveHook < ActiveRecord::Base
  belongs_to :repository

  attr_accessible :name, :url
  
  validates :name, :url, :repository, presence: true

  def deliver_payloads(payloads)
    payloads.each { |payload| deliver_payload payload }
  end

  def deliver_payload(payload)
    uri = URI(url)
    unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS)
      raise HookError.new self, "Invalid URI (#{uri.class}): #{url}" 
    end
    
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = (uri.scheme == "https")

    errmsg = nil
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data "payload" => payload.to_hash.to_json
    res = http.start { |s| s.request request }
    raise HookError.new self, "Response error" unless res.is_a? Net::HTTPSuccess
  rescue SocketError, Timeout::Error, EOFError
    raise HookError.new self, "Request error"
  end

  class HookError < Exception
    attr_accessor :post_receive_hook

    def initialize(post_receive_hook, msg = nil)
      super msg
      self.post_receive_hook = post_receive_hook
    end
  end
end

app/models/post_receive_hook/payload.rb
class PostReceiveHook::Payload

  include ActionDispatch::Routing::UrlFor
  include Rails.application.routes.url_helpers

  attr_accessor :repository, :before, :after, :ref, :project

  def self.parse_refs(repository, refs)
    refs.split("\n").map do |line| 
      before, after, ref = line.to_s.chomp.split " "
      if valid_ref?(ref) && valid_after?(after)
        self.new repository, before, after, ref
      end
    end.compact
  end

  def self.valid_ref?(ref)
    ref.match(/refs\/heads\//).present?
  end

  def self.valid_after?(after)
    !after.match(/^0{40}$/).present?
  end

  def initialize(repository, before, after, ref)
    self.repository = repository
    self.before = before
    self.after = after
    self.ref = ref
    self.project = repository.project
  end

  def to_hash
    @hash ||= {
      before: before,
      after: after,
      ref: ref,
      commits: commits,
      repository: {
        id: repository.id,
        description: project.description,
        fork: false,
        forks: 0,
        master_branch: repository.default_branch,
        homepage: project.homepage,
        name: project.identifier,
        open_issues: project.issues.open.length,
        owner: {
          name: Setting.app_title,
          email: Setting.mail_from
        },
        private: !project.is_public?,
        url: repository_url,
        watchers: project.members.count
      }
    }
  end

  private
  def commits
    # New branch, check from HEAD
    before_rev = before.match(/^0{40}$/) ? "HEAD" : before
    repository.scm.revisions(nil, before_rev, after, reverse: true).map do |rev|
      commit_for_revision(rev)
    end
  end

  def commit_for_revision(revision)
    changes = changes_for_revision(revision)
    {
      id: revision.identifier,
      url: revision_url(revision),
      author: {
        name: revision_author_name(revision),
        email: revision_author_email(revision),
        username: repository.find_committer_user(revision.author)
      },
      message: revision.message,
      timestamp: revision.time,
      added: changes["A"] || [],
      modified: changes["M"] || [],
      removed: changes["D"] || []
    }
  end

  def revision_author_name(revision)
    revision.author.gsub /^([^<]+)\s+.*$/, '\1'
  end

  def revision_author_email(revision)
    revision.author.gsub /^.*<([^>]+)>.*$/, '\1'
  end

  def changes_for_revision(revision)
    revision.paths.map { |p| [p[:action], p[:path]] }.inject({}) do |h, k| 
      h[k[0]] ||= []
      h[k[0]] << k[1]
      h
    end
  end

  def repository_url
    url_for controller: "repositories", action: "show", 
      id: project, only_path: false, 
      host: Setting.host_name, protocol: Setting.protocol
  end

  def revision_url(revision)
    url_for controller: "repositories", action: "revision", 
      id: project, rev: revision.identifier, only_path: false, 
      host: Setting.host_name, protocol: Setting.protocol
  end
end

app/models/post_receive_hook/payload_streamer.rb
class PostReceiveHook::PayloadStreamer
  attr_accessor :payloads, :hooks, :failures

  def initialize(payloads, hooks)
    self.payloads = payloads
    self.hooks = hooks
    self.failures = []
  end

  def outro
    "Thanks for using Redmine Git Server\n"
  end

  def failure_boundary
    "\n*** WARNING ***\n\n"
  end

  def failures_display
    failure_boundary +
    "The following hooks had errors:\n" +
    failures.uniq.map { |f| "\t#{f.name} (#{f.url}) - errors: #{failures.count(f)}\n" }.join +
    "\nDon't panic - your code is fine.\n\n"
  end

  def each
    yield "Beginning post-receive hooks...\n" if payloads.any? && hooks.any?
    payloads.each_with_index do |payload, payload_index|
      yield "Delivering hooks payload #{payload_index + 1} of #{payloads.length}...\n"
      hooks.find_each do |hook|
        begin
          yield "\tPOSTing to hook #{hook.name} - #{hook.url}... "
          hook.deliver_payload payload
          yield "success!\n"
        rescue PostReceiveHook::HookError => error
          yield "\n\n*** Oops! The hook named #{hook.name} failed: #{error.message}\n\n"
          failures << hook
        end
      end
      yield "Delivered payload #{payload_index + 1} of #{payloads.length}\n"
    end
    yield failures_display if failures.any?
    yield outro
  end
end

app/controllers/post_receive_hooks_controller.rb
class PostReceiveHooksController < ApplicationController
  menu_item :repository

  respond_to :html, :json
  respond_to :js, except: [:run, :index]

  skip_before_filter :verify_authenticity_token, :check_if_login_required, 
    only: :run

  before_filter :check_api_enabled, :find_repository_api, only: :run
  before_filter :find_project_and_repository, except: :run
  before_filter :authorize, except: :run
  before_filter :find_post_receive_hook, except: [:run, :index, :new, :create]
  before_filter :check_project
  before_filter :find_repositories, except: :run

  def run
    @repository.fetch_changesets
    deliver_payloads
  end

  def index
    @post_receive_hooks = @repository.post_receive_hooks
    respond_with @post_receive_hooks
  end

  def show
    respond_with @post_receive_hook
  end

  def new
    @post_receive_hook = PostReceiveHook.new
    respond_with @post_receive_hook
  end

  def edit
    respond_with @post_receive_hook
  end

  def create
    @post_receive_hook = PostReceiveHook.new(params[:post_receive_hook])
    @post_receive_hook.repository = @repository
    if @post_receive_hook.save && !request.xhr?
      flash[:notice] = "Post receive hook was successfully created."
    end
    respond_with @post_receive_hook
  end

  def update
    if @post_receive_hook.update_attributes(params[:post_receive_hook]) && !request.xhr?
      flash[:notice] = "Post receive hook was successfully updated."
    end
    respond_with @post_receive_hook
  end

  def destroy
    @post_receive_hook.destroy
    flash[:notice] = "Post receive hook was successfully deleted." unless request.xhr?
    respond_with @post_receive_hook, location: post_receive_hooks_url(@project, @repository)
  end

  def url_options
    return super if params[:action] == "run"
    super.reverse_merge project_id: @project, repository_id: @repository
  end
  

  private
  def check_api_enabled
    User.current = nil
    unless Setting.sys_api_enabled? && params[:key].to_s == Setting.sys_api_key
      msg = "Access denied. Repository management WS is disabled or key is invalid."
      render text: msg, status: 403
    end
  end

  def find_repository_api
    @repository = Repository::GitServer.find params[:repository_id]
    @project = @repository.project
  rescue ActiveRecord::RecordNotFound
    render nothing: true, status: 404
  end

  def find_project_and_repository
    @project = Project.find params[:project_id]
    scope = @project.repositories.where type: Repository::GitServer
    @repository = scope.find params[:repository_id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_post_receive_hook
    @post_receive_hook = @repository.post_receive_hooks.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_repositories
    @repositories = @project.repositories # Needed for repositories sidebar
  end

  def check_project
    render_404_or_api unless @project.present? && @project.active? && \
      @project.module_enabled?(:repository)
  end

  def payloads
    return [] unless hooks.any?
    PostReceiveHook::Payload.parse_refs @repository, request.body.read
  end

  def hooks
    @repository.post_receive_hooks
  end

  def deliver_payloads
    self.response_body = PostReceiveHook::PayloadStreamer.new payloads, hooks
  end

  def render_404_or_api
    if params[:action] == "run"
      render nothing: true, status: 404
    else
      render_404
    end
  end
end

app/views/post_receive_hooks/_form.html.erb
<%= error_messages_for "post_receive_hook" %>

<div class="box tabular">
  <p><%= f.text_field :name %></p>
  <p><%= f.text_field :url %></p>
</div>

app/views/post_receive_hooks/_post_receive_hook.html.erb
<tr>
  <td><%= link_to post_receive_hook.name, post_receive_hook %></td>
  <td><%= post_receive_hook.url %></td>
  <td>
    <%= link_to l(:button_edit), [:edit, post_receive_hook] %> | 
    <%= link_to l(:button_delete), post_receive_hook, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/post_receive_hooks/_post_receive_hook.js.erb
<%# Use full url paths in here because it may be rendered in another controller. %>
<%= div_for post_receive_hook do %>
  <% if User.current.allowed_to?(:manage_post_receive_hooks, @project) %>
    <%= link_to post_receive_hook.name, edit_post_receive_hook_path(@project, @repository, post_receive_hook), remote: true %>
    <%= link_to image_tag("delete.png"), post_receive_hook_path(@project, @repository, post_receive_hook), remote: true, method: :delete, data: { confirm: "Are you sure?" }, style: "vertical-align: middle", class: "delete" %>
  <% else %>
    <%= link_to post_receive_hook.name, post_receive_hook_path(@project, @repository, post_receive_hook), remote: true %>
  <% end %>
<% end %>

app/views/post_receive_hooks/_repositories_sidebar.html.erb
<%# Copied from the default redmine view %>
<% if @repositories.size > 1 %>
  <h3><%= l(:label_repository_plural) %></h3>
  <p>
    <%= @repositories.sort.collect {|repo|
        link_to h(repo.name), 
                {:controller => 'repositories', :action => 'show',
                 :id => @project, :repository_id => repo.identifier_param, :rev => nil, :path => nil},
                :class => 'repository' + (repo == @repository ? ' selected' : '')
      }.join('<br />').html_safe %>
  </p>
<% end %>

app/views/post_receive_hooks/_sidebar.html.erb
<% if ((controller_name == "repositories" && action_name == "show") || controller_name == "post_receive_hooks") && @repository.is_a?(Repository::GitServer) && User.current.allowed_to?(:view_post_receive_hooks, @project) %>
  <%# Be explicit so this view may be rendered by any controller. %>

  <% if User.current.allowed_to?(:manage_post_receive_hooks, @project) %>
    <div class="contextual">
      <%= link_to l(:button_add), new_post_receive_hook_path(@project, @repository), remote: true %>
    </div>
  <% end %>

  <h4><%= l(:label_post_receive_hook_plural) %></h4>

  <div class="post_receive_hooks">
    <%= render partial: "post_receive_hooks/post_receive_hook.js", collection: @repository.post_receive_hooks %>
  </div>
<% end %>

app/views/post_receive_hooks/create.js.erb
<% if @post_receive_hook.valid? %>
  hideModal();
  $("<%= escape_javascript render(@post_receive_hook) %>")
    .appendTo(".post_receive_hooks")
    .effect("highlight");
<% else %>
  $("#errorExplanation").remove();
  $("<%= escape_javascript error_messages_for("post_receive_hook") %>").prependTo("#new_post_receive_hook");
<% end %>

app/views/post_receive_hooks/destroy.js.erb
$("#<%= dom_id @post_receive_hook %>").fadeOut();

app/views/post_receive_hooks/edit.html.erb
<h2><%= l(:label_post_receive_hook_edit) %></h2>

<%= labelled_form_for @post_receive_hook do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  
  <p>
    <%= f.submit l(:button_save) %>
    <%= link_to l(:button_cancel), post_receive_hooks_path %>
  </p>
<% end %>

<% content_for :sidebar do %>
  <%= render "repositories_sidebar" %>
<% end %>

app/views/post_receive_hooks/edit.js.erb
<% form = capture do %>
  <h3 class="title"><%= l(:label_post_receive_hook_edit) %></h3>

  <%= labelled_form_for @post_receive_hook, remote: true do |f| %>
    <%= render partial: "form.html", locals: {f: f} %>

    <p class="buttons">
      <%= f.submit l(:button_save) %>
      <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
    </p>
  <% end %>
<% end %>

$("#ajax-modal")
  .html("<%= escape_javascript form %>")
  .find(".box")
    .css("z-index", "auto");

showModal("ajax-modal", "600px");

app/views/post_receive_hooks/new.html.erb
<h2><%= l(:label_post_receive_hook_new) %></h2>

<%= labelled_form_for @post_receive_hook do |f| %>
  <%= render partial: "form", locals: {f: f} %>
  
  <p>
    <%= f.submit l(:button_create) %>
    <%= link_to l(:button_cancel), post_receive_hooks_path %>
  </p>
<% end %>

<% content_for :sidebar do %>
  <%= render "repositories_sidebar" %>
<% end %>

app/views/post_receive_hooks/new.js.erb
<% form = capture do %>
  <h3 class="title"><%= l(:label_post_receive_hook_new) %></h3>

  <%= labelled_form_for @post_receive_hook, remote: true do |f| %>
    <%= render partial: "form.html", locals: {f: f} %>

    <p class="buttons">
      <%= f.submit l(:button_create) %>
      <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
    </p>
  <% end %>
<% end %>

$("#ajax-modal")
  .html("<%= escape_javascript form %>")
  .find(".box")
    .css("z-index", "auto");

showModal("ajax-modal", "600px");

app/views/post_receive_hooks/show.html.erb
<h2><%= l(:label_post_receive_hook) %></h2>

<div class="box">
  <p>
    <b>Name:</b>
    <%= @post_receive_hook.name %>
  </p>
  <p>
    <b>Url:</b>
    <%= @post_receive_hook.url %>
  </p>
</div>

<%= link_to l(:label_post_receive_hook_edit), [:edit, @post_receive_hook] %> |
<%= link_to l(:button_cancel), @post_receive_hook %>

<% content_for :sidebar do %>
  <%= render "repositories_sidebar" %>
<% end %>

app/views/post_receive_hooks/show.js.erb
<% show = capture do %>
  <h3 class="title"><%= l(:label_post_receive_hook) %></h3>

  <div class="box">
    <dl>
      <dt><%= l(:field_name) %>:</dt>
      <dd><%= @post_receive_hook.name %></dd>
    </dl>

    <dl>
      <dt><%= l(:field_url) %></dt>
      <dd><%= @post_receive_hook.url %></dd>
    </dl>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
  </p>
<% end %>

$("#ajax-modal")
  .html("<%= escape_javascript show %>")
  .find(".box")
    .css("z-index", "auto");

showModal("ajax-modal", "600px");

app/views/post_receive_hooks/update.js.erb
<% if @post_receive_hook.valid? %>
  hideModal();
  $("#<%= dom_id @post_receive_hook %>").replaceWith("<%= escape_javascript render(@post_receive_hook) %>");
  $("#<%= dom_id @post_receive_hook %>").effect("highlight");
<% else %>
  $("#errorExplanation").remove();
  $("<%= escape_javascript error_messages_for("post_receive_hook") %>").prependTo("#edit_post_receive_hook_<%= @post_receive_hook.id %>");
<% end %>