config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  mount GitWit::Engine => "/"

  resources :public_keys, except: [:edit, :update]

  scope "/projects/:project_id/repository/:repository_id" do
    resources :post_receive_hooks
  end

  scope "/repositories/:repository_id" do
    resources :post_receive_hooks, only: [] do
      put "run", on: :collection
    end
  end
end

app/models/public_key.rb
require 'digest'

class PublicKey < ActiveRecord::Base
  belongs_to :user
  attr_accessible :raw_content
  attr_writer :raw_content

  validate :check_raw_content
  validates :content, uniqueness: true

  before_validation :save_raw_content

  EXTRACT_CONTENT = /^(ssh-(?:dss|rsa)\s.*?)(?:\s+(.*)\s*)?$/

  def raw_content
    return @raw_content if @raw_content.present?
    "#{content} #{comment}" if content.present? && comment.present?
  end

  def split_raw_content
    @raw_content.scan(EXTRACT_CONTENT).flatten.map(&:to_s).map(&:chomp)
  end

  def save_raw_content
    self.content, self.comment = split_raw_content if @raw_content.present?
    self.checksum = Digest::MD5.hexdigest(self.content)
  end

  def check_raw_content
    if !@raw_content.present? && !content.present?
      errors.add :raw_content, :blank
    elsif @raw_content.present? && split_raw_content.first.blank?
      errors.add :raw_content, "cannot be parsed"
    end
  end

  def self.authorized_key_map
    key_map = {}
    all.each do |key|
      key_map[key.user.username] ||= []
      key_map[key.user.username] += [key.raw_content]
    end
    key_map
  end

  def self.regenerate_authorized_keys
    GitWit.regenerate_authorized_keys(authorized_key_map)
  end
end

app/controllers/public_keys_controller.rb
class PublicKeysController < ApplicationController

  respond_to :html, :json
  respond_to :js, except: :index

  before_filter :require_login

  before_filter :find_user
  before_filter :find_public_key, :authorize_owner, only: [:show, :destroy]

  def index
    @public_keys = PublicKey.where user_id: @user
    respond_with @public_keys
  end

  def show
    respond_with @public_key
  end

  def new
    @public_key = PublicKey.new
    respond_with @public_key
  end

  def create
    @public_key = PublicKey.new(params[:public_key])
    @public_key.user = @user

    if @public_key.save
      GitWit.add_authorized_key(@user.login, @public_key.raw_content)
      flash[:notice] = "Public key was successfully created." unless request.xhr?
    end
    respond_with @public_key
  end

  def destroy
    @public_key.destroy 
    GitWit.remove_authorized_key(@public_key.raw_content)
    flash[:notice] = "Public key was successfully deleted." unless request.xhr?
    respond_with @public_key
  end

  def find_user
    @user = User.current
  end

  def find_public_key
    @public_key = PublicKey.find params[:id]
  end

  def authorize_owner
    render_403 unless @public_key.user == @user
  end
end

app/views/public_keys/_form.html.erb
<%= error_messages_for "public_key" %>

<div class="box tabular">
  <p><%= f.text_area :raw_content %></p>
</div>

app/views/public_keys/_my_sidebar.html.erb
<%# This file exists because some of the required url parameters are not given
    so it cannot be reused without overriding. %>

<h3><%=l(:label_my_account)%></h3>

<p><%=l(:field_login)%>: <strong><%= link_to_user(@user, :format => :username) %></strong><br />
<%=l(:field_created_on)%>: <%= format_time(@user.created_on) %></p>

<% if @user.own_account_deletable? %>
  <p><%= link_to(l(:button_delete_my_account), {:controller => 'my', :action => 'destroy'}, :class => 'icon icon-del') %></p>
<% end %>

<h4><%= l(:label_feeds_access_key) %></h4>

<p>
<% if @user.rss_token %>
<%= l(:label_feeds_access_key_created_on, distance_of_time_in_words(Time.now, @user.rss_token.created_on)) %>
<% else %>
<%= l(:label_missing_feeds_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:controller => 'my', :action => 'reset_rss_key'}, :method => :post %>)
</p>

<% if Setting.rest_api_enabled? %>
<h4><%= l(:label_api_access_key) %></h4>
<div>
  <%= link_to_function(l(:button_show), "$('#api-access-key').toggle();")%>
  <pre id='api-access-key' class='autoscroll'><%= h(@user.api_key) %></pre>
</div>
<%= javascript_tag("$('#api-access-key').hide();") %>
<p>
<% if @user.api_token %>
<%= l(:label_api_access_key_created_on, distance_of_time_in_words(Time.now, @user.api_token.created_on)) %>
<% else %>
<%= l(:label_missing_api_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:controller => 'my', :action => 'reset_api_key'}, :method => :post %>)
</p>
<% end %>

app/views/public_keys/_public_key.html.erb
<tr>
  <td><%= link_to public_key.comment, public_key %></td>
  <td><%= truncate public_key.content %></td>
  <td><%= link_to l(:button_delete), public_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/public_keys/_public_key.js.erb
<%# Use full url paths in here because it may be rendered in another controller. %>
<%= div_for public_key do %>
  <%= link_to public_key.comment, public_key, remote: true %>
  <%= content_tag :span, class: "splitcontentright" do %>
    <%= link_to l(:button_delete), public_key, remote: true, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
<% end %>

app/views/public_keys/_sidebar.html.erb
<% if controller_name == "public_keys" || (controller_name == "my" && %w(account password).include?(action_name)) %>
  <%# Be explicit so this view may be rendered by any controller. %>
  <h4><%= l(:label_public_key_plural) %></h4>

  <div class="public_keys">
    <%= render partial: "public_keys/public_key.js", collection: @user.public_keys %>
  </div>

  <p>
    <%= link_to l(:label_public_key_new), new_public_key_path, remote: true %>
  </p>
<% end %>

app/views/public_keys/create.js.erb
<% if @public_key.valid? %>
  hideModal();
  $("<%= escape_javascript render(@public_key) %>")
    .appendTo(".public_keys")
    .effect("highlight");
<% else %>
  $("#errorExplanation").remove();
  $("<%= escape_javascript error_messages_for("public_key") %>").prependTo("#new_public_key");
<% end %>

app/views/public_keys/destroy.js.erb
$("#<%= dom_id @public_key %>").fadeOut();

app/views/public_keys/index.html.erb
<h2><%=l(:label_public_key_plural)%></h2>

<% if @public_keys.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>

  <div class="autoscroll">
    <table class="list entries" id="browser">
      <thead>
        <tr id="root">
          <th><%= l(:field_public_key_comment) %></th>
          <th><%= l(:field_public_key_content) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @public_keys %>
      </tbody>
    </table>
  </div>
    
<% end %>

<%= link_to l(:label_public_key_new), new_public_key_path %>

<% content_for :sidebar do %>
  <%= render "my_sidebar" %>
<% end %>

app/views/public_keys/new.html.erb
<h2><%=l(:label_public_key_new)%></h2>

<%= labelled_form_for(@public_key) do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>

  <p>
    <%= f.submit l(:button_create) %>
    <%= link_to l(:button_cancel), public_keys_path %>
  </p>
<% end %>

<% content_for :sidebar do %>
  <%= render "my_sidebar" %>
<% end %>

app/views/public_keys/new.js.erb
<% form = capture do %>
  <h3 class="title"><%= l(:label_public_key_new) %></h3>

  <%= labelled_form_for @public_key, remote: true do |f| %>
    <%= render partial: "form.html", locals: {f: f} %>

    <p class="buttons">
      <%= f.submit l(:button_create) %>
      <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
    </p>
  <% end %>
<% end %>

$("#ajax-modal")
  .html("<%= escape_javascript form %>")
  .find(".box")
    .css("z-index", "auto");

showModal("ajax-modal", "600px");

app/views/public_keys/show.html.erb
<h1><%=l(:label_public_key)%></h1>

<dl>
  <dt><%= l(:field_public_key_comment) %>:</dt>
  <dd><%= @public_key.comment %></dd>
</dl>

<dl>
  <dt><%= l(:field_public_key_content) %></dt>
  <dd><textarea readonly="readonly"><%= @public_key.content %></textarea></dd>
</dl>

<%= link_to l(:button_back), public_keys_path %>

<% content_for :sidebar do %>
  <%= render "my_sidebar" %>
<% end %>

app/views/public_keys/show.js.erb
<% show = capture do %>
  <h3 class="title"><%= l(:label_public_key) %></h3>

  <div class="box">
    <dl>
      <dt><%= l(:field_public_key_comment) %>:</dt>
      <dd><%= @public_key.comment %></dd>
    </dl>

    <dl>
      <dt><%= l(:field_public_key_content) %></dt>
      <dd><textarea readonly="readonly"><%= @public_key.content %></textarea></dd>
    </dl>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_cancel), onclick: "hideModal(this);", type: "button" %>
  </p>
<% end %>

$("#ajax-modal")
  .html("<%= escape_javascript show %>")
  .find(".box")
    .css("z-index", "auto");

showModal("ajax-modal", "600px");